/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Aldeano_Anciano.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function AldeanoAnciano(props) {
  const { nodes, materials } = useGLTF(`${process.env.PUBLIC_URL+'/Aldeano_Anciano.glb'}`)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cuerpo.geometry} material={materials['Material.020']} position={[0, -1.126, 0]} />
      <mesh geometry={nodes.Chaqueta.geometry} material={materials['Material.023']} position={[0, -1.126, 0]} />
      <mesh geometry={nodes.Ceja_der.geometry} material={materials['Material.019']} position={[0, -1.126, 0]} />
      <mesh geometry={nodes.Ceja_izq.geometry} material={materials['Material.019']} position={[0, -1.126, 0]} />
      <mesh geometry={nodes.Nariz001.geometry} material={materials['Material.018']} position={[0, -1.126, 0]} />
      <group position={[0, -1.126, 0]}>
        <mesh geometry={nodes.Mesh_3.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Mesh_6.geometry} material={materials['Material.022']} />
      </group>
      <group position={[0, -1.126, 0]}>
        <mesh geometry={nodes.Mesh_7.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Mesh_8.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Mesh_9.geometry} material={materials['Material.022']} />
      </group>
    </group>
  )
}

useGLTF.preload(`${process.env.PUBLIC_URL+'/Aldeano_Anciano.glb'}`)
