/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sword-normals.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function SwordNormals(props) {
  const { nodes, materials } = useGLTF(`${process.env.PUBLIC_URL+'/sword-normals.glb'}`)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Handler001.geometry} material={materials.Sword} position={[-0.321, 2.665, 0.549]} />
    </group>
  )
}

useGLTF.preload(`${process.env.PUBLIC_URL+'/sword-normals.glb'}`)
