/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sword.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function sword(props) {
  const { nodes, materials } = useGLTF(`${process.env.PUBLIC_URL+'/sword.glb'}`)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Handler001.geometry} material={materials['Material.001']} position={[-0.321, 2.665, 0.549]} />
    </group>
  )
}

useGLTF.preload(`${process.env.PUBLIC_URL+'/sword.glb'}`)
